{
 "title": "Official 1",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Log Stream Avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_logs_incoming_log_events_average",
     "legendFormat": "{{log_group_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 17, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "100 - (rdsosmetrics_memory_active/rdsosmetrics_memory_total) * 100",
     "legendFormat": "{{instance}}-used_memory"
    }
   ]
  },
  {
   "title": "Read_Write Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "aws_rds_read_latency_average", "legendFormat": "{{ instance }}-read-latency" },
    { "expr": "aws_rds_write_latency_average", "legendFormat": "{{ instance }}-write-latency" }
   ]
  },
  {
   "title": "Task Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rdsosmetrics_loadAverageMinute_one",
     "legendFormat": "{{instance}}-load_Avg"
    }
   ]
  },
  {
   "title": "Connection Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_rds_database_connections_average",
     "legendFormat": "{{instance}}-connections_avg"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "The panel shows the total CPU usage.",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 30 },
   "yaxes": [
    { "format": "percent", "label": "CPU_Usage (%)" }
   ],
   "targets": [
    {
     "expr": "rdsosmetrics_cpuUtilization_total",
     "legendFormat": "{{instance}}-total_cpu_usage"
    }
   ]
  }
 ]
}